- name: Setup MySQL
  become: true
  block:
    - name: Ensure /opt/mysql directory is present
      ansible.builtin.file:
        path: /opt/mysql
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml for MySQL
      ansible.builtin.copy:
        src: mysql/docker-compose.yml
        dest: /opt/mysql/docker-compose.yml
        mode: '0644'

    - name: Start MySQL container
      community.docker.docker_compose:
        project_src: /opt/mysql
        state: present
      environment:
        MYSQL_ROOT_PASSWORD: "{{ top_mysql_root_password }}"

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: PyMySQL
        state: present

- name: Create bigben_test database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ top_mysql_root_password }}"

    name: bigben_test
    state: present

- name: Create bigben_test user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ top_mysql_root_password }}"

    name: bigben_test_app
    host: '%'
    password: "{{ top_bigben_test_app_mysql_password }}"
    priv: "bigben_test.*:SELECT,INSERT,UPDATE,DELETE"

- name: Create bigben_test_migration user
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ top_mysql_root_password }}"

    name: bigben_test_migration
    host: '%'
    password: "{{ top_bigben_test_migration_mysql_password }}"
    priv: "bigben_test.*:ALL"
