- name: Commit firewall configuration
  ansible.builtin.command:
    cmd: uci commit firewall
  changed_when: true

- name: Restart firewall
  ansible.builtin.service:
    name: firewall
    state: restarted

- name: Commit DHCP configuration
  ansible.builtin.command:
    cmd: uci commit dhcp
  changed_when: true

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
