- name: Include secret variables
  ansible.builtin.include_vars: secrets.yml
  no_log: true

# Python must often be bootstrapped on OpenWRT.
# This is relatively idempotent, so it's safe to run it every time.
- name: Bootstrap Python
  ansible.builtin.raw: opkg update && opkg install python3
  changed_when: true

- name: Install the required packages
  community.general.opkg:
    update_cache: true
    name:
      - ddns-scripts
      - ddns-scripts-cloudflare
      - curl
      - ca-bundle

# This shouldn't be necessary, but it was for me.
# I think it's because OpenWRT has recently migrated some dependencies.
# I found this idea here: https://www.sobyte.net/post/2023-02/openwrt-ddns-cloudflare/#google_vignette
- name: Add Cloudflare service line
  ansible.builtin.lineinfile:
    line: '"cloudflare.com-v4" "update_cloudflare_com_v4.sh"'
    path: /etc/ddns/services

# This command is idempotent, so it's safe to run it every time.
- name: Configure ddns-scripts
  ansible.builtin.blockinfile:
    path: /etc/config/ddns
    block: |
      config service 'cloudflare'
          option 'service_name' 'cloudflare.com-v4'
          option 'enabled'      '1'
          option 'domain'       '{{ ddns_cloudflare_domain }}'
          option 'username'     'Bearer'
          option 'password'     '{{ ddns_cloudflare_api_key }}'
          option 'interface'    'wan'
          option 'ip_source'    'web'
          option 'ip_url'       'http://ipv4.icanhazip.com'
  notify:
    - Commit ddns configuration
    - Restart ddns
