version: '3.8'

x-common:
  chimer: &chimer
    image: ghcr.io/glizzus/bigben/chimer:${CHIMER_TAG}
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
      DEBUG: chimer:*

services:
  campa:
    image: ghcr.io/glizzus/bigben/campa:${CAMPA_TAG}
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      REDIS_HOST: ${REDIS_HOST}
      MARIADB_URI: ${MARIADB_URI}
      DEBUG: campa*

  chimer1:
    <<: *chimer

  chimer2:
    <<: *chimer

  chimer3:
    <<: *chimer

  flyway:
    image: ghcr.io/glizzus/bigben/flyway:${FLYWAY_TAG}
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 20
